# Generated by Django 3.1.5 on 2021-02-24 07:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country_slogan', models.CharField(max_length=255, unique=True)),
                ('country_highlight', ckeditor_uploader.fields.RichTextUploadingField()),
                ('country_detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail_image', models.ImageField(upload_to='country/thumbnail/')),
                ('cover_image', models.ImageField(upload_to='country/')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
