# Generated by Django 3.1.5 on 2022-03-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='package/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='package/thumbnail/'),
        ),
    ]
