# Generated by Django 3.1.5 on 2021-02-14 08:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=255)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tour_done', models.IntegerField()),
                ('years', models.IntegerField()),
                ('happy_client', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='about')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
