# Generated by Django 3.1.5 on 2021-02-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
    ]
