# Generated by Django 3.1.5 on 2021-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service_icon', models.ImageField(upload_to='services')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Our Services',
            },
        ),
    ]
