# Generated by Django 3.1.5 on 2021-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_name', models.CharField(blank=True, max_length=2, null=True, verbose_name=(('0', 'Everest'), ('1', 'Annapurna'), ('2', 'Langtang'), ('3', 'Dolpo')))),
                ('avatar', models.ImageField(upload_to='review')),
                ('review', models.TextField()),
            ],
            options={
                'verbose_name': 'Review',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Our Service'},
        ),
    ]
