# Generated by Django 3.1.5 on 2021-03-02 07:09

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210211_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover_image', '1650x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
