# Generated by Django 3.1.5 on 2021-05-22 07:40

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover_image', '750x375', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
