# Generated by Django 3.1.5 on 2021-02-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_seo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('phone', 'whatsapp', 'email', 'office_address'), 'verbose_name': 'Company Address'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Company Logo'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO'},
        ),
        migrations.AlterModelOptions(
            name='socialsettings',
            options={'verbose_name': 'Social Setting'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Company Title'},
        ),
    ]
