# Generated by Django 3.1.5 on 2021-02-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20210215_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Company Address'},
        ),
    ]
